#!/bin/bash

rm -rf output
mkdir output
ruby ../deck_gen/deck_generator.rb --file crisis_deck.yaml,common_salvage_deck.yaml,rare_salvage_deck.yaml,survivor_deck.yaml,emplacement_deck.yaml,mutation_deck.yaml > output/everything.html
ruby ../deck_gen/deck_generator.rb --file helper_deck.yaml,survivor_deck.yaml  -c 3  > output/helper.html
cp deck_style.css                                                                           output/style.css
cp -r assets                                                                                output/assets

wkpdf --source output/everything.html --paper letter --orientation landscape --margins 0 --print-background yes         --output output/master.pdf
wkpdf --source output/helper.html --paper letter --orientation landscape --margins 0 --print-background yes         --output output/helper.pdf
